[package]
name = "rotate-image"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["ImageData", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
