name: Deploy demo page to GitHub Pages
on: 
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Do checkout
        uses: actions/checkout@v3
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build wasm module
        run: wasm-pack build --target web
      - name: Copy products to ./demo directory
        run: cp -r pkg/ demo/ && rm demo/pkg/.gitignore
      - name: Deploy files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo